chore: codecov chane file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,8 +37,5 @@ jobs:
           FOLDER: build # The folder the action should deploy.
           TARGET_FOLDER: /
 
-      - name: cov
-        run: ls ./coverage
-
       - name: Codecov
-        run: bash <(curl -s https://codecov.io/bash) -f './coverage' -t ${{ secrets.CODECOV_TOKEN }} || echo 'Codecov failed to upload'
+        run: bash <(curl -s https://codecov.io/bash) -f './coverage/clover.xml' -t ${{ secrets.CODECOV_TOKEN }} || echo 'Codecov failed to upload'
